[tool.poetry]
name = "flask"
version = "3.10"
description = "no"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "y"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
